### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Sumanth214** [AdilBaaj/unsupervised-image-retrieval#1]
Thanks for the nice article of CBIR that you are done. I am a researcher i want  to  build a model for  Search for individuals in a database with similar face attributes based on input image.I thought your code is helpful to me for my research.Can i use LFW dataset having the faces instead of MNIST dataset for implementing the model on face search. Can you please give suggestion to achieve this.

**Comment by AdilBaaj** [comment]
Hi @Sumanth214 ! The current code is not suitable for a face recognition task. I am not even sure that you can achieve good results for face recognition using an autoencoder. If you still want to try, your best chance would be to implement the model mentioned on Geoffrey Hinton's paper [Using Very Deep Autoencoders for Content-Based Image Retrieval](https://pdfs.semanticscholar.org/8808/0d28536f36588740737f3b7a1f6c1a409654.pdf).
Let me know if you get good results!
